#server:
#  port: 8081

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888

#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/fitness_user_db
#    username: postgres
#    password: 12345678
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
#    prefer-ip-address: true